# Generated by Django 3.1.3 on 2021-01-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firname', models.CharField(max_length=20)),
                ('lasname', models.CharField(max_length=20)),
                ('positioner', models.CharField(choices=[('WD', 'Web'), ('BD', 'Backend'), ('FD', 'Frontend'), ('SD', 'Senior'), ('DS', 'Designer')], max_length=2)),
            ],
        ),
    ]
